[build] 
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/a"
  to = "https://kan-test-netlify-functions.netlify.com/.netlify/functions/slug"
  status = 200
  force = true
  headers = {X-From = "SLUG-A", X-Netlify-Hostname = "a.com"}

[[redirects]]
  from = "/b"
  to = "https://kan-test-netlify-functions.netlify.com/.netlify/functions/slug"
  status = 200
  force = true
  headers = {X-From = "SLUG-B", X-Netlify-Hostname = "b.com"}
