[build] 
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/host1"
  to = "https://kan-test-netlify-functions.netlify.com/.netlify/functions/from"
  status = 200
  force = true
  headers = {X-From = "SLUG-A", X-Netlify-Hostname: "host1.com"}

[[redirects]]
  from = "/host2"
  to = "https://kan-test-netlify-functions.netlify.com/.netlify/functions/from"
  status = 200
  force = true
  headers = {X-From = "SLUG-B", X-Netlify-Hostname: "host2.com"}
